import numpy as np

In [1]:
#khai báo

import numpy as np

py_list = [1, 2, 3, 5, 6, 7] #list rời rạc

np_list =np.array(py_list)  #gom 1 kiểu, xử lí nhanh
type(np_list) #xuất kiểu 
#đa chiều ,...

numpy.ndarray

# np array chỉ sp được 1 kiểu dữ liệu trong 1 arr
# list sp được nhiều kiểu dữ liệu trong 1 list

In [2]:
#example
py_list = [2, 4, 4.6, 1/2]
np_list = np.array(py_list) # numpy array chỉ sử dụng được 1 kiểu 
np_list

array([2. , 4. , 4.6, 0.5])

In [3]:
np_list_type = np_list.astype(int) #chuyển đổi kiểu dữ liệu np arr 
np_list_type #hiển thị

array([2, 4, 4, 0])

In [4]:
x = np.array(range(1,9)) # tạo 1 mảng từ 1 đến 8 
#2 x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x


array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# cách lấy số 3 vị trí
x[2]

np.int64(3)

In [6]:
# x = [start:end:step] step default = 1
# phần tử cần lấy (end - start) sẽ ra được
x[1:8:1]

array([2, 3, 4, 5, 6, 7, 8])

In [7]:
# cách khác để lấy hết mảng
x[0::]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
# đảo ngược mảng
x[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [9]:
#vừa lấy giá trị 7 và 8

x[-2], x[-1]

(np.int64(7), np.int64(8))

In [10]:
#lấy giá trị tìm vị trí
x[  [2, 4]  ]

array([3, 5])

In [11]:
x[[3,5]]

array([4, 6])